// https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_code_values

export const KEYCODES = {
  Digit0: "0",
  Digit1: "1",
  Digit2: "2",
  Digit3: "3",
  Digit4: "4",
  Digit5: "5",
  Digit6: "6",
  Digit7: "7",
  Digit8: "8",
  Digit9: "9",
  Numpad0: "0",
  Numpad1: "1",
  Numpad2: "2",
  Numpad3: "3",
  Numpad4: "4",
  Numpad5: "5",
  Numpad6: "6",
  Numpad7: "7",
  Numpad8: "8",
  Numpad9: "9",
  KeyA: "A",
  KeyB: "B",
  KeyC: "C",
  KeyD: "D",
  KeyE: "E",
  KeyF: "F",
  KeyG: "G",
  KeyH: "H",
  KeyI: "I",
  KeyJ: "J",
  KeyK: "K",
  KeyL: "L",
  KeyM: "M",
  KeyN: "N",
  KeyO: "O",
  KeyP: "P",
  KeyQ: "Q",
  KeyR: "R",
  KeyS: "S",
  KeyT: "T",
  KeyU: "U",
  KeyV: "V",
  KeyW: "W",
  KeyX: "X",
  KeyY: "Y",
  KeyZ: "Z",
};

export const INVALID_KEYCODES = {
  Minus: "-",
  Equal: "=",
  Backspace: "\u232B",
  BracketLeft: "[",
  BracketRight: "]",
  Enter: "\u23CE",
  Semicolon: ";",
  Quote: "'",
  Backquote: "`",
  Backslash: "\\",
  Comma: ",",
  Period: ".",
  Slash: "/",
  Space: "\u2423",
  Home: "\u21F1",
  End: "\u21F2",
  PageUp: "\u21DE",
  PageDown: "\u21DF",
  ArrowUp: "\u2191",
  ArrowDown: "\u2193",
  ArrowLeft: "\u2190",
  ArrowRight: "\u2192",
  Insert: "\u2380",
  Delete: "\u2326",
  NumpadAdd: "+",
  NumpadSubtract: "-",
  NumpadMultiply: "*",
  NumpadDivide: "/",
  NumpadDecimal: ".",
  NumpadEnter: "\u23CE",
  NumpadEqual: "=",
  NumpadComma: ",",
};

export const MODIFIERS = {
  Alt: "Alt",
  Ctrl: "Ctrl",
  Meta: "Super", // Tauri global shortcut plugin allows only "SUPER"
  Shift: "Shift",
};
