[package]
name = "deskulpt"
version = "0.0.0"
description = "Deskulpt (Desktop + Sculpture), a cross-platform desktop customization tool."
authors = ["Xinyu Li", "Yao Xiao", "Yuchen Zhou", "David Zhu"]
edition = "2021"

[build-dependencies]
tauri-build = "1.5.1"

[dev-dependencies]
pretty_assertions = "1.4.0"
parameterized = "2.0.0"

[dependencies]
tauri = { version = "1.6.1", features = ["shell-open"] }

# Utilities
anyhow = "1.0.80"
normpath = "1.2.0"
path-clean = "1.0.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.1"

# SWC crates and related
parking_lot = "0.12.1"  # Required by swc_ecma_loader
swc_atoms = "0.6.5"
swc_bundler = "0.225.13"
swc_common = { version = "0.33.19", features = ["tty-emitter"] }
swc_ecma_ast = "0.112.5"
swc_ecma_codegen = "0.148.10"
swc_ecma_loader = { version = "0.45.21", features = ["node"] }
swc_ecma_minifier = "0.192.19"
swc_ecma_parser = "0.143.8"
swc_ecma_transforms_react = "0.183.13"
swc_ecma_visit = "0.98.6"

[features]
custom-protocol = ["tauri/custom-protocol"]
