[package]
name = "deskulpt"
version = "0.0.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-beta.13", features = ["codegen"] }

[dev-dependencies]
cargo-llvm-cov = "0.6.11"
copy_dir = "0.1.3"
pretty_assertions = "1.4.0"
regex = "1.10.6"
rstest = "0.22.0"

[dependencies]
tauri = { version = "2.0.0-beta.23", features = ["macos-private-api", "test", "tray-icon"] }
tauri-plugin-clipboard-manager = "2.1.0-beta.5"
tauri-plugin-global-shortcut = "2.0.0-beta.7"
tauri-plugin-shell = "2.0.0-beta.8"

# Utilities
anyhow = "1.0.86"
path-clean = "1.0.1"
serde = { version = "1.0.208", features = ["derive"] }
serde-error = "0.1.2"
serde_json = "1.0.125"
tempfile = "3.10.1"

# APIs
sysinfo = "0.31.2"

# SWC crates and related
parking_lot = "0.12.3"  # Required by swc_ecma_loader
swc_atoms = "0.6.7"
swc_bundler = "0.226.0"
swc_common = "0.33.25"
swc_ecma_ast = "0.113.0"
swc_ecma_codegen = "0.149.0"
swc_ecma_loader = "0.45.27"
swc_ecma_minifier = "0.193.1"
swc_ecma_parser = "0.144.0"
swc_ecma_transforms_optimization = "0.199.0"
swc_ecma_transforms_react = "0.184.0"
swc_ecma_transforms_typescript = "0.189.0"
swc_ecma_visit = "0.99.0"

[target."cfg(target_os = \"macos\")".dependencies]
objc = "0.2.7"

[features]
custom-protocol = ["tauri/custom-protocol"]
