[package]
name = "deskulpt"
version = "0.0.0"
description = "Deskulpt (Desktop + Sculpt, pronounced /'desk ålpt/), a cross-platform desktop customization tool."
authors = ["Xinyu Li", "Yao Xiao", "Yuchen Zhou", "Frank Zhu"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5.1", features = ["config-json5"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
parameterized = "2.0.0"
cargo-llvm-cov = "0.6.9"
rstest = "0.19.0"

[dependencies]
tauri = { version = "1.6.1", features = ["shell-open", "config-json5", "test"] }

# Utilities
anyhow = "1.0.80"
normpath = "1.2.0"
path-clean = "1.0.1"
serde = { version = "1.0.197", features = ["derive"] }
serde-error = "0.1.2"
serde_json = "1.0.1"
tempfile = "3.10.1"

# SWC crates and related
parking_lot = "0.12.1"  # Required by swc_ecma_loader
swc_atoms = "0.6.5"
swc_bundler = "0.225.13"
swc_common = "0.33.19"
swc_ecma_ast = "0.112.5"
swc_ecma_codegen = "0.148.10"
swc_ecma_loader = "0.45.21"
swc_ecma_minifier = "0.192.19"
swc_ecma_parser = "0.143.8"
swc_ecma_transforms_optimization = "0.198.18"
swc_ecma_transforms_react = "0.183.13"
swc_ecma_visit = "0.98.6"

[features]
custom-protocol = ["tauri/custom-protocol"]
