name: Setup Rust
description: Setup Rust environment for Deskulpt workflows.

inputs:
  platform:
    description: The platform to set up on.
    type: choice
    required: true
    default: ubuntu-latest
    options:
      - ubuntu-latest
      - macos-latest
      - windows-latest

  targets:
    description: Rust setup targets.
    type: string
    required: true
    default: ""

  components:
    description: Additional Rust components to install on top of the minimal profile.
    type: string
    required: true
    default: ""

  tools:
    description: Additional tools to install.
    type: string
    required: false

  nightly-rustfmt:
    description: Whether to install rustfmt from the nightly toolchain.
    type: boolean
    required: true
    default: false

  cache-key:
    description: The cache key.
    type: string
    required: true
    default: ""

  save-cache:
    description: Whether to save the cache.
    type: boolean
    required: true
    default: false

runs:
  using: composite
  steps:
    - name: Install Linux dependencies
      if: inputs.platform == 'ubuntu-latest'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev

    - name: Setup toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}

    - name: Setup cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: . -> target
        shared-key: ${{ inputs.cache-key }}
        save-if: ${{ inputs.save-cache == 'true' }}
        cache-bin: false

    - name: Install nightly rustfmt
      if: ${{ inputs.nightly-rustfmt }}
      shell: bash
      run: |
        rustup toolchain install nightly --component rustfmt --profile minimal --no-self-update

    - name: Install tools
      uses: taiki-e/install-action@v2
      if: ${{ inputs.tools }}
      with:
        tool: ${{ inputs.tools }}
