name: Setup Node
description: Composite action to set up the node environment for Deskulpt workflows.

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Node setup and cache
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: pnpm

    - name: Install frontend dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
