name: Setup Node
description: Setup Node environment for Deskulpt workflows.

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Node setup
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    # https://github.com/rolldown/rolldown/blob/8f346736079d3e1280302dc7f18f95eaa1b0bb29/.github/actions/setup-node/action.yml

    - name: Find pnpm store
      id: store
      shell: bash
      run: echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - name: Save and restore pnpm cache
      uses: actions/cache@v4
      if: ${{ github.ref_name == 'main' }}
      with:
        path: ${{ steps.store.outputs.PNPM_STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store-

    - name: Restore pnpm cache
      uses: actions/cache/restore@v4
      if: ${{ github.ref_name != 'main' }}
      with:
        path: ${{ steps.store.outputs.PNPM_STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-

    - name: Install node dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
