version: 2
updates:
  # Deskulpt core
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    labels:
      - "type: maintenance"

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: daily
    labels:
      - "type: maintenance"

  # Deskulpt tooling
  - package-ecosystem: npm
    directory: /tooling/apis
    schedule:
      interval: daily
    labels:
      - "type: maintenance"

  - package-ecosystem: npm
    directory: /tooling/react
    schedule:
      interval: daily
    labels:
      - "type: maintenance"

  - package-ecosystem: npm
    directory: /tooling/ui
    schedule:
      interval: daily
    labels:
      - "type: maintenance"

  # Website
  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: daily
    labels:
      - "type: maintenance"
