version: 2
updates:
  # Rust dependencies
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      rust:
        patterns:
          - "*"

  # Node dependencies
  # TODO: Documentation dependencies should have a separate group, but we cannot
  # because of the issue with pnpm workspace:
  # https://github.com/dependabot/dependabot-core/issues/7501
  # We may also want to rework the documentation setup in the future
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      node:
        patterns:
          - "*"

  # CI dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      ci:
        patterns:
          - "*"
