version: 2
updates:
  # Core and tooling (frontend)
  - package-ecosystem: npm
    directories:
      - /
      - /tooling/apis
      - /tooling/react
      - /tooling/ui
    schedule:
      interval: weekly
    labels:
      - dependencies
    ignore:
      - dependency-name: "eslint"
        versions: ["9.x"]
    groups:
      tauri:
        patterns:
          - "@tauri-apps/*"
      dev:
        dependency-type: development

  # Core and tooling (backend)
  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      tauri:
        patterns:
          - tauri*
      swc:
        patterns:
          - swc*
      dev:
        dependency-type: development

  # Website
  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
      dev:
        dependency-type: development

  # Maintenance
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
