# Configuration file for automatically adding labels for PRs based on changed files, to
# be used by `pull-request-labeler.yaml`; see https://github.com/actions/labeler

"type:doc":
  - changed-files:
      - any-glob-to-any-file:
          - website/**

"type:maintenance":
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
          - maint_tools/**

"tooling:apis":
  - changed-files:
      - any-glob-to-any-file:
          - tooling/apis/**
          - src-tauri/src/apis/**

"tooling:emotion":
  - changed-files:
      - any-glob-to-any-file:
          - tooling/emotion/**

"tooling:react":
  - changed-files:
      - any-glob-to-any-file:
          - tooling/react/**
