# Configuration file for automatically adding labels for PRs based on changed files, to
# be used by `pull-request-labeler.yaml`; see https://github.com/actions/labeler

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - src/**
          - views/**

backend:
  - changed-files:
      - any-glob-to-any-file:
          - src-tauri/**

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - website/**

maintenance:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
          - maint_tools/**
