name: Setup Deskulpt
description: Composite action to set up the environment for Deskulpt workflows.

inputs:
  platform:
    description: The platform to set up on.
    type: choice
    required: true
    default: ubuntu-latest
    options:
      - ubuntu-latest
      - macos-latest
      - windows-latest
  targets:
    description: Rust setup targets.
    type: string
    required: true
    default: ""
  lint:
    description: Whether to do additional setup for linting.
    type: boolean
    required: true
    default: false
  format:
    description: Whether to do additional setup for formatting.
    type: boolean
    required: true
    default: false

runs:
  using: composite
  steps:
    - name: Install Linux dependencies
      if: inputs.platform == 'ubuntu-latest'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev

    - name: Rust setup
      uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.lint == 'true' && 'clippy' || '' }}
        targets: ${{ inputs.targets }}

    - name: Install formatting tools
      if: inputs.format == 'true'
      shell: bash
      run: |
        rustup toolchain install nightly --component rustfmt --profile minimal --no-self-update
        curl -fsSL https://github.com/tamasfe/taplo/releases/latest/download/taplo-linux-x86_64.gz | \
          gzip -d - | install -m 755 /dev/stdin /usr/local/bin/taplo

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: . -> target

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Node setup and cache
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: pnpm

    - name: Install frontend dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
