packages:
  - packages/*
  - docs

catalog:
  "@emotion/react": ^11.14.0
  "@emotion/babel-plugin": ^11.13.5
  "@radix-ui/themes": ^3.2.0
  "@rollup/plugin-replace": ^6.0.2
  "@rollup/plugin-terser": ^0.4.4
  "@rollup/plugin-typescript": ^12.1.4
  "@tauri-apps/api": ^2.8.0
  "@tauri-apps/plugin-clipboard-manager": ^2.3.0
  "@tauri-apps/plugin-opener": ^2.5.0
  "@types/node": ^24.7.2
  "@types/react": ^19.2.2
  "@types/react-dom": ^19.2.1
  "@vitejs/plugin-react": ^5.0.4
  re-resizable: ^6.11.2
  react: ^19.2.0
  react-dom: ^19.2.0
  react-draggable: ^4.5.0
  react-error-boundary: ^6.0.0
  react-icons: ^5.5.0
  rollup: ^4.52.4
  sonner: ^2.0.7
  tslib: ^2.8.1
  typescript: ^5.9.3
  vite: ^7.1.9
  zustand: ^5.0.8
