[package]
name        = "deskulpt"
description = "Deskulpt, a cross-platform desktop customization tool."
version     = { workspace = true }
authors     = { workspace = true }
edition     = { workspace = true }
homepage    = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }

[dependencies]
anyhow                         = { workspace = true }
deskulpt-core                  = { workspace = true }
path-clean                     = { workspace = true }
serde                          = { workspace = true, features = ["derive"] }
serde_json                     = { workspace = true }
tauri                          = { workspace = true, features = ["macos-private-api", "tray-icon"] }
tauri-plugin-clipboard-manager = { workspace = true }
tauri-plugin-global-shortcut   = { workspace = true }

[target."cfg(target_os = \"macos\")".dependencies]
objc = { workspace = true }

[dev-dependencies]
async-std             = { workspace = true, features = ["attributes"] }
copy_dir              = { workspace = true }
rstest                = { workspace = true }
tauri                 = { workspace = true, features = ["test"] }
tempfile              = { workspace = true }

[build-dependencies]
tauri-build = { workspace = true, features = ["codegen"] }

[package.metadata.docs.rs]
rustdoc-args = ["--document-private-items"]
