// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Shortcuts } from "./Shortcuts";
import type { Theme } from "./Theme";

/**
 * Application-wide settings.
 */
export type AppSettings = { 
/**
 * The application theme.
 */
theme: Theme, 
/**
 * The keyboard shortcuts.
 */
shortcuts: Shortcuts, };
