// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppSettings } from "./AppSettings";
import type { WidgetSettings } from "./WidgetSettings";

/**
 * Full settings of the application.
 */
export type Settings = { 
/**
 * Application-wide settings.
 */
app: AppSettings, 
/**
 * The mapping from widget IDs to their respective settings.
 */
widgets: { [key in string]?: WidgetSettings }, };
