// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Keyboard shortcuts registered in the application.
 *
 * A keyboard shortcut being `None` means that it is disabled, otherwise it is
 * a string parsable into [`Shortcut`](tauri_plugin_global_shortcut::Shortcut).
 */
export type Shortcuts = { 
/**
 * For toggling canvas interaction mode.
 */
toggleCanvasImode: string | null, 
/**
 * For opening the manager window.
 */
openManager: string | null, };
