// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Application-wide settings.
 */
export type AppSettings = { 
/**
 * The application theme.
 */
theme: Theme, 
/**
 * The keyboard shortcuts.
 */
shortcuts: Shortcuts, };

export type DeskulptWindow = "manager" | "canvas";

/**
 * Event for exiting the application.
 *
 * This event is emitted from the backend to the manager window when the
 * application needs to be closed for it to persist the states before exiting.
 */
export type ExitAppEvent = null;

/**
 * Event for the initial render of the application.
 *
 * This event is emitted from the backend to the canvas window when we are sure
 * that it is ready for the initial render.
 */
export type RenderWidgetsEvent = Array<RenderWidgetsEventInner>;

/**
 * Inner structure for [`RenderWidgetsEvent`].
 */
export type RenderWidgetsEventInner = { 
/**
 * The ID of the widget being rendered.
 */
id: string, 
/**
 * If provided, update the settings of the widget.
 */
settings: WidgetSettings | null, 
/**
 * If provided, update the code of the widget.
 */
code: string | null, };

/**
 * Full settings of the application.
 */
export type Settings = { 
/**
 * Application-wide settings.
 */
app: AppSettings, 
/**
 * The mapping from widget IDs to their respective settings.
 */
widgets: { [key in string]?: WidgetSettings }, };

/**
 * Keyboard shortcuts registered in the application.
 *
 * A keyboard shortcut being `None` means that it is disabled, otherwise it is
 * a string parsable into [`Shortcut`](tauri_plugin_global_shortcut::Shortcut).
 */
export type Shortcuts = { 
/**
 * For toggling canvas interaction mode.
 */
toggleCanvasImode: string | null, 
/**
 * For opening the manager window.
 */
openManager: string | null, };

/**
 * Event for showing a toast notification.
 *
 * This event is emitted from the backend to the canvas window when a toast
 * notification needs to be displayed.
 */
export type ShowToastEvent = { "type": "SUCCESS", "content": string } | { "type": "ERROR", "content": string };

/**
 * Light/dark theme of the application.
 */
export type Theme = "light" | "dark";

/**
 * Full configuration of a Deskulpt widget.
 */
export type WidgetConfig = { "type": "VALID", "content": { 
/**
 * The directory name of the widget.
 */
dir: string, 
/**
 * Display name of the widget.
 */
name: string, 
/**
 * Entry file of the widget source code.
 */
entry: string, 
/**
 * External dependencies of the widget as in `package.json`.
 */
dependencies: { [key in string]?: string }, } } | { "type": "INVALID", "content": { 
/**
 * The directory name of the widget.
 */
dir: string, 
/**
 * Error message.
 */
error: string, } };

/**
 * Per-widget settings.
 *
 * Different from widget configurations, these are independent of the widget
 * configuration files and are managed internally by the application.
 */
export type WidgetSettings = { 
/**
 * The leftmost x-coordinate in pixels.
 */
x: number, 
/**
 * The topmost y-coordinate in pixels.
 */
y: number, 
/**
 * The opacity in percentage.
 */
opacity: number, };
