// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Application-wide settings.
 */
export type AppSettings = { 
/**
 * The application theme.
 */
theme: Theme, 
/**
 * Canvas interaction mode.
 */
canvasImode: CanvasImode, 
/**
 * The keyboard shortcuts.
 */
shortcuts: Shortcuts, };

export type AppSettingsUpdate = { "field": "THEME", value: Theme, } | { "field": "CANVAS_IMODE", value: CanvasImode, } | { "field": "SHORTCUTS", value: ShortcutsUpdate, };

/**
 * Canvas interaction mode.
 */
export type CanvasImode = "SINK" | "FLOAT";

/**
 * Deskulpt window enum.
 */
export type DeskulptWindow = "manager" | "canvas";

/**
 * Event for exiting the application.
 *
 * This event is emitted from the backend to the manager window when the
 * application needs to be closed for it to persist the states before exiting.
 */
export type ExitAppEvent = null;

/**
 * Event for removing widgets.
 *
 * This event is emitted from the manager window to the canvas window when
 * widgets need to be removed.
 */
export type RemoveWidgetsEvent = Array<string>;

/**
 * Event for re-rendering widgets.
 *
 * This event is mainly emitted from the manager window to the canvas window
 * when settings or code of a widget needs to be re-rendered. It may also be
 * emitted from the backend to the canvas window for the initial render.
 */
export type RenderWidgetsEvent = Array<RenderWidgetsEventInner>;

/**
 * Inner structure for [`RenderWidgetsEvent`].
 */
export type RenderWidgetsEventInner = { 
/**
 * The ID of the widget being re-rendered.
 */
id: string, 
/**
 * If provided, update the settings of the widget.
 */
settings?: WidgetSettings, 
/**
 * If provided, update the code of the widget.
 */
code?: string, };

/**
 * Full settings of the application.
 */
export type Settings = { 
/**
 * Application-wide settings.
 */
app: AppSettings, 
/**
 * The mapping from widget IDs to their respective settings.
 */
widgets: { [key in string]?: WidgetSettings }, };

export type SettingsUpdate = { "field": "APP", value: AppSettingsUpdate, } | { "field": "WIDGET", key: string, value: WidgetSettingsUpdate, };

/**
 * Keyboard shortcuts registered in the application.
 *
 * A keyboard shortcut being `None` means that it is disabled, otherwise it is
 * a string parsable into [`Shortcut`](tauri_plugin_global_shortcut::Shortcut).
 */
export type Shortcuts = { 
/**
 * For toggling canvas interaction mode.
 */
toggleCanvasImode: string | null, 
/**
 * For opening the manager window.
 */
openManager: string | null, };

export type ShortcutsUpdate = { "field": "TOGGLE_CANVAS_IMODE", value: string | null, } | { "field": "OPEN_MANAGER", value: string | null, };

/**
 * Event for showing a toast notification.
 *
 * This event is emitted from the backend to the canvas window when a toast
 * notification needs to be displayed.
 */
export type ShowToastEvent = { "type": "SUCCESS", "content": string } | { "type": "ERROR", "content": string };

/**
 * Event for switching the app theme.
 *
 * This event is emitted from the manager window to the canvas window when the
 * theme is switched from the manager side.
 */
export type SwitchThemeEvent = Theme;

/**
 * Light/dark theme of the application.
 */
export type Theme = "light" | "dark";

/**
 * Event for updating settings of a widget.
 *
 * This event is emitted between the manager window and the canvas window to
 * each other when widget settings are updated on one side.
 */
export type UpdateSettingsEvent = { 
/**
 * The ID of the widget being updated.
 */
id: string, 
/**
 * [`WidgetSettings::x`](crate::settings::WidgetSettings::x)
 */
x?: number, 
/**
 * [`WidgetSettings::y`](crate::settings::WidgetSettings::y)
 */
y?: number, 
/**
 * [`WidgetSettings::opacity`](crate::settings::WidgetSettings::opacity)
 */
opacity?: number, };

/**
 * Full configuration of a Deskulpt widget.
 */
export type WidgetConfig = { "type": "VALID", "content": { 
/**
 * The directory name of the widget.
 */
dir: string, 
/**
 * Display name of the widget.
 */
name: string, 
/**
 * Entry file of the widget source code.
 */
entry: string, 
/**
 * External dependencies of the widget as in `package.json`.
 */
dependencies: { [key in string]?: string }, } } | { "type": "INVALID", "content": { 
/**
 * The directory name of the widget.
 */
dir: string, 
/**
 * Error message.
 */
error: string, } };

/**
 * Per-widget settings.
 *
 * Different from widget configurations, these are independent of the widget
 * configuration files and are managed internally by the application.
 */
export type WidgetSettings = { 
/**
 * The leftmost x-coordinate in pixels.
 */
x: number, 
/**
 * The topmost y-coordinate in pixels.
 */
y: number, 
/**
 * The opacity in percentage.
 */
opacity: number, };

export type WidgetSettingsUpdate = { "field": "X", value: number, } | { "field": "Y", value: number, } | { "field": "OPACITY", value: number, };
