// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-widget settings.
 *
 * Different from widget configurations, these are independent of the widget
 * configuration files and are managed internally by the application.
 */
export type WidgetSettings = { 
/**
 * The leftmost x-coordinate in pixels.
 */
x: number, 
/**
 * The topmost y-coordinate in pixels.
 */
y: number, 
/**
 * The opacity in percentage.
 */
opacity: number, };
