// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Full configuration of a Deskulpt widget.
 */
export type WidgetConfig = { "type": "VALID", "content": { 
/**
 * The directory name of the widget.
 */
dir: string, 
/**
 * Display name of the widget.
 */
name: string, 
/**
 * Entry file of the widget source code.
 */
entry: string, 
/**
 * External dependencies of the widget as in `package.json`.
 */
dependencies: { [key in string]?: string }, } } | { "type": "INVALID", "content": { 
/**
 * The directory name of the widget.
 */
dir: string, 
/**
 * Error message.
 */
error: string, } };
