fn main() {
    deskulpt_build::Builder::default()
        .commands(&[
            "bundle_widget",
            "call_plugin",
            "emit_on_render_ready",
            "exit_app",
            "open_widget",
            "rescan_widgets",
            "set_render_ready",
            "update_settings",
        ])
        .events(&[
            "ExitAppEvent",
            "RemoveWidgetsEvent",
            "RenderWidgetsEvent",
            "ShowToastEvent",
            "SwitchThemeEvent",
            "UpdateSettingsEvent",
        ])
        .build();
}
