import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

export default {
  guides: [
    {
      type: "autogenerated",
      dirName: "guides",
    },
  ],
  development: [
    {
      type: "autogenerated",
      dirName: "development",
    },
    {
      type: "category",
      label: "References",
      link: {
        type: "generated-index",
        title: "References",
      },
      items: [
        {
          type: "link",
          label: "Backend",
          href: "https://csci-shu-410-se-project.github.io/Deskulpt/rustdoc/deskulpt_test/",
          description: "Rust documentation for the Deskulpt backend.",
        },
        {
          type: "category",
          label: "Frontend",
          items: require("./docs/tsdoc/typedoc-sidebar.cjs"),
          description: "TypeScript documentation for the Deskulpt frontend.",
        },
      ],
    },
  ],
} satisfies SidebarsConfig;
