import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  guides: [{ type: "autogenerated", dirName: "guides" }],
  tsdoc: [{ type: "autogenerated", dirName: "tsdoc" }],
};

export default sidebars;
