name: Build Deskulpt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RUST_BACKTRACE: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Fail the job
        run: exit 1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: ./src-tauri -> target

      - name: Node setup and cache
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install frontend dependencies
        run: npm install

      # Without specifying `tagName` and `releaseId`, tauri-action will only build the
      # application without trying to upload any assets
      - name: Build Deskulpt
        id: build-deskulpt
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.platform }}
          path: "${{ join(fromJSON(steps.build-deskulpt.outputs.artifactPaths), '\n') }}"

  comment-success:
    needs: build
    if: always() && needs.build.result == 'success' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Get short commit SHA
        id: short-sha
        run: |
          shortsha=$(echo ${{ github.sha }} | cut -c 1-7)
          echo "sha=$shortsha" >> $GITHUB_OUTPUT

      - name: Find comment
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: |
            .github/workflows/build.yaml

      - name: Post success comment
        if: "always() && (needs.build.result == 'success')"
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |-
            ## ✔️ Deskulpt Built Successfully!

            Deskulpt binaries have been built successfully on all supported platforms.
            Your pull request is in excellent shape! ☀️

            <sub>
              Workflow file: `.github/workflows/build.yaml`.
              Generated for commit:
              [`${{ steps.short-sha.outputs.sha }}`](https://github.com/${{ github.repository }}/pull/${{ github.event.number }}/commits/${{ github.sha }}).
              Link to the built binaries:
              [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            </sub>
          edit-mode: replace

  comment-failure:
    needs: build
    if: always() && needs.build.result != 'success' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Get short commit SHA
        id: short-sha
        run: |
          shortsha=$(echo ${{ github.sha }} | cut -c 1-7)
          echo "sha=$shortsha" >> $GITHUB_OUTPUT

      - name: Find comment
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: |
            .github/workflows/build.yaml

      - name: Post failure comment
        if: "always() && (needs.build.result != 'success')"
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |-
            ## ❌ Failed to Build Deskulpt

            There seems to be some issues with the build process for certain platforms.
            Please check the logs to see what went wrong and fix the issues accordingly.

            <sub>
              Workflow file: `.github/workflows/build.yaml`.
              Generated for commit:
              [`${{ steps.short-sha.outputs.sha }}`](https://github.com/${{ github.repository }}/pull/${{ github.event.number }}/commits/${{ github.sha }}).
              Link to the failing workflow run:
              [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            </sub>
          edit-mode: replace
