name: Cache Warmup

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache-debug:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: ./.github/actions/setup-rust
        with:
          platform: ${{ matrix.platform }}
          cache-key: debug
          save-cache: true

      - name: Populate Rust cache
        run: |
          cargo check
          cargo build
          cargo test --no-run
