name: Doc build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: ./src-tauri -> target

      - name: Build Rust docs
        run: |
          cd src-tauri
          cargo doc --no-deps

      - name: Build TypeScript docs
        run: |
          cd src
          npx typedoc

      - name: Node setup and cache
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install doc dependencies
        run: |
          npm install
          cd website
          npm install

      - name: Build docs
        run: |
          cd website
          npm run build

      - name: Copy Rust docs to build directory
        run: |
          rm -f src-tauri/target/doc/.lock
          cp -r src-tauri/target/doc website/build/rustdoc

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/build

  deploy:
    needs: build
    if: github.event_name == 'push' # Do not deploy on PRs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
