name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Needed for last updated time

      - uses: ./.github/actions/setup-rust
        with:
          platform: ubuntu-latest
          cache-key: debug
          components: rust-docs

      - uses: ./.github/actions/setup-node

      - name: Build docs
        run: pnpm docs:build

      - name: Build rustdoc
        run: |
          cargo docs
          rm -f target/doc/.lock
          cp -r target/doc/ docs/.vitepress/dist/rustdoc/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-dist
          path: docs/.vitepress/dist

  docs-deploy:
    needs: docs-build
    if: github.event_name == 'push'
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v5
        with:
          name: docs-dist
          path: docs-dist

      - name: Deploy to github.io repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY_KEY }}
          external_repository: deskulpt-apps/deskulpt-apps.github.io
          publish_branch: main
          publish_dir: docs-dist
