name: Lint Deskulpt tooling

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RUST_BACKTRACE: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Node setup and cache
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install shared dependencies
        run: npm install

      - name: Lint @deskulpt-test/react
        run: |
          cd tooling/react
          npm install
          npm run lint

      - name: Lint @deskulpt-test/raw-apis
        run: |
          cd tooling/raw-apis
          npm install
          npm run lint
