name: Lint PR Title

on:
  pull_request_target:
    types: [opened, edited, reopened]

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
            release
          requireScope: false
