name: Lint Deskulpt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RUST_BACKTRACE: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          lint: true
          platform: ${{ matrix.platform }}

      - name: Check code formatting
        if: matrix.platform == 'ubuntu-latest'
        run: pnpm format:check

      - name: Check code linting
        run: pnpm lint:check
