name: Lint Deskulpt tooling

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Node setup and cache
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install shared dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint @deskulpt-test/react
        run: |
          cd tooling/react
          pnpm lint

      - name: Lint @deskulpt-test/apis
        run: |
          cd tooling/apis
          pnpm lint

      - name: Lint @deskulpt-test/ui
        run: |
          cd tooling/ui
          pnpm lint
