name: Release

on:
  push:
    tags:
      - "v[0-9]+*"

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: ./.github/actions/setup-rust
        with:
          platform: ${{ matrix.platform }}
          cache-key: release

      - uses: ./.github/actions/setup-node

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "Deskulpt v__VERSION__"
          releaseDraft: true
          prerelease: false
