name: Release

on:
  push:
    tags:
      - "v[0-9]+*"

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest # Arm-based macOS (M1 and above)
            args: --target aarch64-apple-darwin
          - platform: macos-latest # Intel-based macOS
            args: --target x86_64-apple-darwin
          - platform: ubuntu-latest
            args: ""
          - platform: windows-latest
            args: ""
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          platform: ${{ matrix.platform }}
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}
          tagName: v__VERSION__
          releaseName: "Deskulpt v__VERSION__"
          releaseDraft: true
          prerelease: false
          releaseBody: |
            ## Download Deskulpt v__VERSION__

            | Platform              | Format        | Download                                                                                                                                                      |
            |-----------------------|---------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------|
            | Linux                 | RPM package   | [Deskulpt-__VERSION__-1.x86_64.rpm](https://github.com/CSCI-SHU-410-SE-Project/Deskulpt/releases/download/v__VERSION__/Deskulpt-__VERSION__-1.x86_64.rpm)     |
            | Linux                 | DEB package   | [Deskulpt___VERSION___amd64.deb](https://github.com/CSCI-SHU-410-SE-Project/Deskulpt/releases/download/v__VERSION__/Deskulpt___VERSION___amd64.deb)           |
            | Linux                 | AppImage      | [Deskulpt___VERSION___amd64.AppImage](https://github.com/CSCI-SHU-410-SE-Project/Deskulpt/releases/download/v__VERSION__/Deskulpt___VERSION___amd64.AppImage) |
            | macOS (Apple Silicon) | DMG installer | [Deskulpt___VERSION___aarch64.dmg](https://github.com/CSCI-SHU-410-SE-Project/Deskulpt/releases/download/v__VERSION__/Deskulpt___VERSION___aarch64.dmg)       |
            | macOS (Apple Silicon) | Tarball       | [Deskulpt_aarch64.app.tar.gz](https://github.com/CSCI-SHU-410-SE-Project/Deskulpt/releases/download/v__VERSION__/Deskulpt_aarch64.app.tar.gz)                 |
            | macOS (Intel)         | DMG installer | [Deskulpt___VERSION___x64.dmg](https://github.com/CSCI-SHU-410-SE-Project/Deskulpt/releases/download/v__VERSION__/Deskulpt___VERSION___x64.dmg)               |
            | macOS (Intel)         | Tarball       | [Deskulpt_x64.app.tar.gz](https://github.com/CSCI-SHU-410-SE-Project/Deskulpt/releases/download/v__VERSION__/Deskulpt_x64.app.tar.gz)                         |
            | Windows               | MSI installer | [Deskulpt___VERSION___x64_en-US.msi](https://github.com/CSCI-SHU-410-SE-Project/Deskulpt/releases/download/v__VERSION__/Deskulpt___VERSION___x64_en-US.msi)   |
            | Windows               | EXE installer | [Deskulpt___VERSION___x64-setup.exe](https://github.com/CSCI-SHU-410-SE-Project/Deskulpt/releases/download/v__VERSION__/Deskulpt___VERSION___x64-setup.exe)   |
