name: Release

on:
  push:
    tags:
      - "v[0-9]+*"

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest # Arm-based macOS (M1 and above)
            args: --target aarch64-apple-darwin
          - platform: macos-latest # Intel-based macOS
            args: --target x86_64-apple-darwin
          - platform: ubuntu-latest
            args: ""
          - platform: windows-latest
            args: ""
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          platform: ${{ matrix.platform }}
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "Deskulpt v__VERSION__"
          releaseBody: |
            See the assets to download this version of Deskulpt and install.
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
