name: Release

on:
  push:
    tags:
      - "v[0-9]+*"

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            target: aarch64-apple-darwin
          - platform: macos-latest
            target: x86_64-apple-darwin
          - platform: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: ./.github/actions/setup-rust
        with:
          platform: ${{ matrix.platform }}
          targets: ${{ matrix.target }}

      - uses: ./.github/actions/setup-node

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --target ${{ matrix.target }}
          tagName: v__VERSION__
          releaseName: "Deskulpt v__VERSION__"
          releaseDraft: true
          prerelease: false
